title: Naivedya Bansal
description: Software Engineer | Building scalable solutions at Mastercard
url: "https://yourusername.github.io"
baseurl: ""

# Theme settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default" # alternatives: air, contrast, dark, dirt, mint, sunrise

# Site Author
author:
  name: "Naivedya Bansal"
  avatar: "/img/passport_photo.jpg" # add your photo to this path
  bio: "Senior Software Engineer at Google"
  location: "Dublin"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/naivedyabansal"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/naivedya-bansal-998a91111/"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/naivedyabansal"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/naivedya-bansal-998a91111/"

atom_feed:
  hide: true    # Hides the feed icon/link

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-include-cache
  - jekyll-remote-theme

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock 